# Use the official Python base image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the requirements file to the container
COPY ./requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY ./ .

# Expose the port your application listens on
EXPOSE 8000

# Run the command to start the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
