version: '3.8'

services:
  cometlabs:
    build:
      context: .
      dockerfile: CometLabs-Dockerfile
    image: cometlabs:dev
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .current.env
    ports:
      - 8005:8000
    stdin_open: true
    tty: true
